IMAGE r2_menu_bg "r2_menu_bg.png" FAST ALL
IMAGE r2_top_right_patch "r2_top_right_patch.png" FAST ALL
IMAGE r2_selector "r2_selector.png" FAST ALL
IMAGE r2_river_0 "r2_river_0.png" FAST ALL
IMAGE r2_river_1 "r2_river_1.png" FAST ALL
IMAGE r2_river_2 "r2_river_2.png" FAST ALL
IMAGE r2_river_3 "r2_river_3.png" FAST ALL
IMAGE r2_river_4 "r2_river_4.png" FAST ALL
IMAGE r2_river_5 "r2_river_5.png" FAST ALL
IMAGE r2_river_6 "r2_river_6.png" FAST ALL
IMAGE r2_river_7 "r2_river_7.png" FAST ALL
IMAGE r2_flag_right_0 "r2_flag_right_0.png" FAST ALL
IMAGE r2_flag_right_1 "r2_flag_right_1.png" FAST ALL
IMAGE r2_flag_right_2 "r2_flag_right_2.png" FAST ALL
IMAGE r2_flag_right_3 "r2_flag_right_3.png" FAST ALL
IMAGE r2_flag_right_4 "r2_flag_right_4.png" FAST ALL
IMAGE r2_flag_right_5 "r2_flag_right_5.png" FAST ALL
IMAGE r2_flag_right_6 "r2_flag_right_6.png" FAST ALL
IMAGE r2_flag_right_7 "r2_flag_right_7.png" FAST ALL
IMAGE r2_fire_top_0 "r2_fire_top_0.png" FAST ALL
IMAGE r2_fire_top_1 "r2_fire_top_1.png" FAST ALL
IMAGE r2_fire_top_2 "r2_fire_top_2.png" FAST ALL
IMAGE r2_fire_top_3 "r2_fire_top_3.png" FAST ALL
IMAGE r2_fire_top_4 "r2_fire_top_4.png" FAST ALL
IMAGE r2_fire_top_5 "r2_fire_top_5.png" FAST ALL
IMAGE r2_fire_top_6 "r2_fire_top_6.png" FAST ALL
IMAGE r2_fire_top_7 "r2_fire_top_7.png" FAST ALL
IMAGE r2_fire_bottom_0 "r2_fire_bottom_0.png" FAST ALL
IMAGE r2_fire_bottom_1 "r2_fire_bottom_1.png" FAST ALL
IMAGE r2_fire_bottom_2 "r2_fire_bottom_2.png" FAST ALL
IMAGE r2_fire_bottom_3 "r2_fire_bottom_3.png" FAST ALL
IMAGE r2_fire_bottom_4 "r2_fire_bottom_4.png" FAST ALL
IMAGE r2_fire_bottom_5 "r2_fire_bottom_5.png" FAST ALL
IMAGE r2_fire_bottom_6 "r2_fire_bottom_6.png" FAST ALL
IMAGE r2_fire_bottom_7 "r2_fire_bottom_7.png" FAST ALL
